# Generated by Django 5.0.1 on 2024-05-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_address_vehicle_email_vehicle_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalan',
            name='location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chalan',
            name='offence_committed',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='chalan',
            name='vehicle_class',
            field=models.CharField(choices=[('motorcycle/scooter', 'Motorcycle/Scooter'), ('car', 'Car')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chalan',
            name='violator_type',
            field=models.CharField(choices=[('owner', 'Owner')], default=None, max_length=20, null=True),
        ),
    ]
